---
- hosts: localhost
  become: no

  pre_tasks:
    - name: Checking for AWS mandatory env vars
      fail: msg="Mandatory env var {{ item }} not found."
      when: lookup('env', item) == ''
      with_items:
        - "AWS_DEFAULT_REGION"
        - "AWS_SECRET_ACCESS_KEY"
        - "AWS_ACCESS_KEY_ID"

  tasks:
    - name: Applying Terraform (may take several minutes)
      shell: >
        terraform apply
      args:
        chdir: "{{ playbook_dir }}/terraform"
      register: tf_apply_raw
      changed_when: not (tf_apply_raw.stdout|search('0 added, 0 changed, 0 destroyed'))

    - name: Getting Terraform's output 'bastion_ip'
      shell: >
        terraform output bastion_ip
      args:
        chdir: "{{ playbook_dir }}/terraform"
      register: bastion_ip_raw
      changed_when: false

    - name: Adding 'bastion_ip' to host group 'bastions'
      add_host:
        name="{{ bastion_ip_raw.stdout }}"
        groups=bastions
        ansible_ssh_private_key_file="secrets/newvizzboard.pem"
        ansible_user="admin"
      changed_when: false

    - name: Waiting for bastion to be reachable via ssh
      wait_for:
        port=22
        host="{{ bastion_ip_raw.stdout }}"
        search_regex=OpenSSH
        delay=10
        timeout=300

- hosts: bastions
  become: yes

  pre_tasks:
    - name: Ansible-ization
      script: >
        {{ playbook_dir }}/ansible/scripts/ansible-seed-debian.sh
      register: ansible_seed
      changed_when: ansible_seed.rc == 0
      failed_when: ansible_seed.rc != 0 and ansible_seed.rc != 42

  roles:
    - common
    - gocd-server
    - gocd-agent
    - cloud-toolbox
