---
- name: adding nginx official repository key
  apt_key:
    url="http://nginx.org/keys/nginx_signing.key"
    state=present

- name: adding nginx official repository
  apt_repository:
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - "deb http://nginx.org/packages/mainline/debian/ {{ ansible_distribution_release }} nginx"
    - "deb-src http://nginx.org/packages/mainline/debian/ {{ ansible_distribution_release }} nginx"

- name: installing nginx
  apt:
    pkg=nginx
    state=present
