---
- hosts: all
  become: yes

  pre_tasks:
    - name: ansible-ization
      script: >
        files/ansible-seed-debian.sh
      register: ansible_seed
      changed_when: ansible_seed.rc == 0
      failed_when: ansible_seed.rc != 0 and ansible_seed.rc != 42

  roles:
    - common
    - gocd-server
    - gocd-agent
    - cloud-toolbox

  tasks:
    - copy:
        src="{{ playbook_dir }}/../secrets/gitlab_deploy_key"
        dest="/var/go/.ssh/id_rsa"
        owner="go"
        group="go"
        mode="0600"